# Generated by Django 5.2.4 on 2025-11-22 16:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='author_image'),
        ),
    ]
